
let sims=[],orders=JSON.parse(localStorage.hg_orders||"[]");const $=id=>document.getElementById(id),money=n=>Number(n).toLocaleString("vi-VN")+" đ";
async function init(){const local=JSON.parse(localStorage.hg_inventory||"null");sims=local||await fetch("data/sims.json").then(r=>r.json());loadSettings();render()}
function save(){localStorage.hg_inventory=JSON.stringify(sims);localStorage.hg_orders=JSON.stringify(orders)}
function render(){const q=($("adminSearch").value||"").toLowerCase().replaceAll(".","");const a=sims.filter(s=>s.number.replaceAll(".","").includes(q));$("inventoryTable").innerHTML=a.map(s=>`<tr><td>${s.id}</td><td><b>${s.number}</b></td><td>${s.network}</td><td>${s.type}</td><td>${money(s.price)}</td><td>${s.status==="sold"?"Đã bán":"Còn hàng"}</td><td><button onclick="editSim('${s.id}')">Sửa</button> <button onclick="toggleSold('${s.id}')">${s.status==="sold"?"Mở bán":"Đã bán"}</button></td></tr>`).join("");$("ordersTable").innerHTML=orders.map(o=>`<tr><td>${o.time}</td><td><b>${o.number}</b></td><td>${o.name}</td><td>${o.phone}</td><td>${o.note||""}</td><td>${o.status}</td></tr>`).join("")||"<tr><td colspan='6'>Chưa có đơn hàng.</td></tr>";const av=sims.filter(s=>s.status==="available");$("dashAvailable").textContent=av.length;$("dashSold").textContent=sims.length-av.length;$("dashOrders").textContent=orders.filter(o=>o.status==="Mới").length;$("dashValue").textContent=money(av.reduce((a,s)=>a+s.price,0))}
function openModal(html){$("modalBody").innerHTML=html;$("modal").classList.add("show")}function closeModal(){$("modal").classList.remove("show")}function toast(x){$("toast").textContent=x;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2200)}
function addSim(){openModal(`<h2>Thêm SIM</h2><div class="form"><input id="newNumber" placeholder="Số SIM *"><select id="newNetwork"><option>Viettel</option><option>VinaPhone</option><option>MobiFone</option><option>Vietnamobile</option></select><input id="newType" placeholder="Dạng số: Tam hoa, Tứ quý..."><input id="newCategory" placeholder="Mã: tam-hoa / tu-quy / ngu-quy / so-tien / de-nho"><input id="newPrice" type="number" placeholder="Giá VNĐ *"><button class="goldBtn" onclick="saveNew()">Thêm vào kho</button></div>`)}
function saveNew(){const n=$("newNumber").value.trim(),p=+$("newPrice").value;if(!n||!p)return toast("Vui lòng nhập số và giá");sims.unshift({id:"HG"+Date.now().toString().slice(-8),number:n,network:$("newNetwork").value,type:$("newType").value||"SIM số đẹp",category:$("newCategory").value||"de-nho",price:p,status:"available",featured:false});save();closeModal();render();toast("Đã thêm SIM")}
function editSim(id){const s=sims.find(x=>x.id===id);openModal(`<h2>Sửa SIM</h2><div class="form"><input id="editNumber" value="${s.number}"><select id="editNetwork"><option ${s.network==="Viettel"?"selected":""}>Viettel</option><option ${s.network==="VinaPhone"?"selected":""}>VinaPhone</option><option ${s.network==="MobiFone"?"selected":""}>MobiFone</option><option ${s.network==="Vietnamobile"?"selected":""}>Vietnamobile</option></select><input id="editType" value="${s.type}"><input id="editCategory" value="${s.category}"><input id="editPrice" type="number" value="${s.price}"><button class="goldBtn" onclick="saveEdit('${id}')">Lưu thay đổi</button></div>`)}
function saveEdit(id){const s=sims.find(x=>x.id===id);s.number=$("editNumber").value.trim();s.network=$("editNetwork").value;s.type=$("editType").value;s.category=$("editCategory").value;s.price=+$("editPrice").value||0;save();closeModal();render();toast("Đã cập nhật")}
function toggleSold(id){const s=sims.find(x=>x.id===id);s.status=s.status==="sold"?"available":"sold";save();render();toast("Đã đổi trạng thái")}
function exportCSV(){const rows=[["id","number","network","type","category","price","status","featured"],...sims.map(s=>[s.id,s.number,s.network,s.type,s.category,s.price,s.status,s.featured])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="shop-sim-hoang-gia-kho-sim.csv";a.click()}
function importCSV(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const lines=r.result.replace(/^\ufeff/,"").trim().split(/\r?\n/).slice(1);lines.forEach((line,i)=>{const p=line.split(",").map(x=>x.replace(/^"|"$/g,""));if(p[1])sims.push({id:p[0]||"IMP"+Date.now()+i,number:p[1],network:p[2]||"Viettel",type:p[3]||"SIM số đẹp",category:p[4]||"de-nho",price:+p[5]||0,status:p[6]||"available",featured:p[7]==="true"})});save();render();toast("Đã nhập CSV")};r.readAsText(f,"utf-8")}
function resetData(){if(!confirm("Khôi phục dữ liệu mẫu và xóa đơn demo?"))return;fetch("data/sims.json").then(r=>r.json()).then(x=>{sims=x;orders=[];save();render();toast("Đã khôi phục")})}
function saveSettings(){localStorage.hg_name=$("shopName").value;localStorage.hg_phone=$("shopPhone").value;localStorage.hg_zalo=$("shopZalo").value;toast("Đã lưu cài đặt")}
function loadSettings(){$("shopName").value=localStorage.hg_name||"SHOP SIM HOÀNG GIA";$("shopPhone").value=localStorage.hg_phone||"";$("shopZalo").value=localStorage.hg_zalo||""}
$("addSimBtn").onclick=addSim;$("adminSearch").oninput=render;$("exportBtn").onclick=exportCSV;$("importInput").onchange=e=>importCSV(e.target);$("resetBtn").onclick=resetData;$("saveSettings").onclick=saveSettings;$("modalClose").onclick=closeModal;$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".adminTab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});init();
