CREATE TABLE IF NOT EXISTS sims (
  id BIGSERIAL PRIMARY KEY,
  number VARCHAR(30) UNIQUE NOT NULL,
  network VARCHAR(30) NOT NULL,
  type VARCHAR(80) DEFAULT 'SIM số đẹp',
  category VARCHAR(40) DEFAULT 'de-nho',
  price BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'available',
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGSERIAL PRIMARY KEY,
  sim_id BIGINT REFERENCES sims(id) ON DELETE SET NULL,
  number VARCHAR(30) NOT NULL,
  customer_name VARCHAR(120) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  note TEXT DEFAULT '',
  status VARCHAR(30) NOT NULL DEFAULT 'Mới',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sims_status ON sims(status);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
